# pbrt-v4 Blender add-on ï¿?exporter (scene -> .pbrt) + pbrt GPU render button.
# Minimal v1: bakes world transforms into geometry (no Transform statement),
# exports perspective camera, SUN/POINT/AREA lights, triangle-mesh shapes with
# an "uber" material (base color + roughness + metallic). Texture mapping and
# more material types are follow-ups.

import bpy
import mathutils
import math
import os


# pbrt expects parameter values space-separated inside [ ]; helpers below build
# the literals.
def _floats(vals):
    return " ".join("%.8g" % v for v in vals)


def _rgb(color):
    # color is a sequence of 3 floats in [0,1]
    return _floats(color[:3])


def _write_mesh(f, obj):
    mesh = obj.data
    mesh.calc_loop_triangles()
    mw = obj.matrix_world
    # rotation part for normals
    rot = mw.to_3x3()

    P = []
    N = []
    idx = []
    n = 0
    for tri in mesh.loop_triangles:
        for li in tri.loops:
            v = mesh.vertices[mesh.loops[li].vertex_index]
            p = mw @ v.co
            P += [p.x, p.y, p.z]
            nrm = rot @ v.normal
            nrm.normalize()
            N += [nrm.x, nrm.y, nrm.z]
            idx.append(n)
            n += 1

    f.write('AttributeBegin\n')
    f.write('  Shape "trianglemesh"\n')
    f.write('    "point3 P" [%s]\n' % _floats(P))
    f.write('    "integer indices" [%s]\n' % _floats(idx))
    # material
    mat = obj.active_material if obj.active_material else None
    if mat and mat.use_nodes:
        bsdf = mat.node_tree.nodes.get("Principled BSDF")
        if bsdf:
            base = bsdf.inputs["Base Color"].default_value
            rough = bsdf.inputs["Roughness"].default_value
            f.write('  Material "coateddiffuse" "rgb reflectance" [%s] '
                    '"float roughness" [%s]\n' % (_rgb(base), rough))
        else:
            f.write('  Material "diffuse" "rgb reflectance" [0.8 0.8 0.8]\n')
    else:
        f.write('  Material "diffuse" "rgb reflectance" [0.8 0.8 0.8]\n')
    f.write('AttributeEnd\n')


def _write_lights(f, scene):
    wrote = False
    for obj in scene.objects:
        if obj.type != 'LIGHT':
            continue
        wrote = True
        ld = obj.data
        energy = ld.energy * 0.01  # scale Blender energy into a sane range
        col = [energy, energy, energy]
        if ld.type == 'SUN':
            f.write('LightSource "distant" "rgb L" [%s]\n' % _floats(col))
        elif ld.type == 'POINT':
            p = obj.location
            f.write('LightSource "point" "rgb I" [%s] "point3 from" [%s]\n' %
                    (_floats(col), _floats([p.x, p.y, p.z])))
        elif ld.type == 'AREA':
            # approximate area light with a point for v1
            p = obj.location
            f.write('LightSource "point" "rgb I" [%s] "point3 from" [%s]\n' %
                    (_floats([c * 2 for c in col]), _floats([p.x, p.y, p.z])))
        else:
            f.write('LightSource "infinite" "rgb L" [%s]\n' % _floats(col))
    if not wrote:
        # ensure the scene is not pitch black
        f.write('LightSource "infinite" "rgb L" [0.5 0.5 0.5]\n')


def export_pbrt(context, filepath):
    scene = context.scene
    cam = scene.camera
    with open(filepath, 'w') as f:
        f.write('# Generated by pbrt Blender add-on (v1)\n')
        if cam is not None:
            mw = cam.matrix_world
            pos = mw.translation
            # camera looks down its local -Z; up is local +Y
            fwd = (mw @ mathutils.Vector((0, 0, -1)) - pos).normalized()
            up = (mw @ mathutils.Vector((0, 1, 0)) - pos).normalized()
            tgt = pos + fwd
            f.write('LookAt %s %s %s\n' % (_floats([pos.x, pos.y, pos.z]),
                                            _floats([tgt.x, tgt.y, tgt.z]),
                                            _floats([up.x, up.y, up.z])))
            # vertical fov from lens (mm); full-frame height = 24 mm (half = 12)
            fov = 2.0 * math.degrees(math.atan(12.0 / cam.data.lens))
            f.write('Camera "perspective" "float fov" [%s]\n' % fov)
        res_x = int(scene.render.resolution_x * scene.render.resolution_percentage / 100)
        res_y = int(scene.render.resolution_y * scene.render.resolution_percentage / 100)
        exr = os.path.splitext(filepath)[0].replace('\\', '/') + '.exr'
        f.write('Film "rgb" "string filename" ["%s"] "integer xresolution" [%d] "integer yresolution" [%d]\n' % (exr, res_x, res_y))
        f.write('Sampler "zsobol" "integer pixelsamples" [16]\n')
        f.write('Integrator "path"\n')
        f.write('WorldBegin\n')
        _write_lights(f, scene)
        for obj in scene.objects:
            if obj.type == 'MESH':
                _write_mesh(f, obj)
        f.write('WorldEnd\n')
    return filepath

